<p><h3><b>TERMOS E CONDI&Ccedil;&Otilde;ES DE USO DO AMBIENTE VIRTUAL</b></h3></p>
<br/>
<p><h4>1. Aceita&ccedil;&atilde;o dos Termos e Condi&ccedil;&otilde;es de Uso</h4>
1.1 Ao fazer uso do Site de Treinamentos na Modalidade Educa&ccedil;&atilde;o Dist&acirc;ncia do Elearning EaD, Voc&ecirc; (a partir de agora denominado Usu&aacute;rio) concorda que leu, entendeu e aceitou os termos, regras e condi&ccedil;&otilde;es aqui dispostos.<br />
1.2 O Elearning EaD se reserva o direito de modificar a qualquer momento a apresenta&ccedil;&atilde;o, configura&ccedil;&atilde;o e disponibiliza&ccedil;&atilde;o do Site, sem que cause preju&iacute;zo ao Usu&aacute;rio. O mesmo se aplica a estes Termos e Condi&ccedil;&otilde;es de Uso, estabelecidos como condi&ccedil;&atilde;o fundamental para a utiliza&ccedil;&atilde;o do Servi&ccedil;o.</p>
<br/>
<p><h4>2. Site</h4>
2.1 O Elearning EaD oferece ao Usu&aacute;rio um Site que permite a navega&ccedil;&atilde;o em seu conte&uacute;do e que se encontra hospedado nos servidores do pr&oacute;prio Elearning EaD.<br />
2.2 &Eacute; obriga&ccedil;&atilde;o do Elearning EaD fornecer Suporte T&eacute;cnico ao Usu&aacute;rio em caso de problemas relacionados ao processo de transmiss&atilde;o online dos Treinamentos no que tange a estabilidade e pleno funcionamento do Ambiente Virtual de Aprendizagem.</p>
<br/>
<p><h4>3. Registros e dados pessoais/ Privacidade de Dados</h4>
3.1 O Usu&aacute;rio declara veracidade de todos os dados por ele fornecidos ao Site no momento de seu Cadastro e em qualquer atualiza&ccedil;&atilde;o posterior, ficando respons&aacute;vel, portanto, pela sua exatid&atilde;o e autenticidade.<br />
3.2 &Eacute; dever do Usu&aacute;rio manter atualizados os dados pessoais fornecidos quando da utiliza&ccedil;&atilde;o do Site. &Eacute; baseado nestes dados que ser&aacute; emitido o Diploma/Certificado de Conclus&atilde;o dos Treinamentos. Caso os dados estejam errados, n&atilde;o &eacute; responsabilidade do Elearning EaD a emiss&atilde;o de novo Documento de Conclus&atilde;o gratuitamente.<br />
3.3 O Elearning EaD preserva a privacidade dos dados dos Usu&aacute;rios e se compromete a revelar os dados apenas a um dos seguintes motivos.<br />
por lei;<br />
por meio de uma ordem ou intima&ccedil;&atilde;o de um &oacute;rg&atilde;o, autoridade ou tribunal com poderes para tanto e de jurisdi&ccedil;&atilde;o competente;<br />
para garantir a seguran&ccedil;a dos sistemas, resguardar direitos e prevenir responsabilidades do Elearning EaD.<br />
3.3 O Elearning EaD pode cancelar qualquer registro de Usu&aacute;rio, a qualquer momento e sem pr&eacute;vio aviso, assim que tiver conhecimento, e a seu exclusivo crit&eacute;rio, de o Usu&aacute;rio descumprir, intencionalmente ou n&atilde;o, estes Termos e Condi&ccedil;&otilde;es de Uso, ou violar leis e regulamentos federais, estaduais e/ou municipais, ou violar os princ&iacute;pios legais, a moral e os bons costumes.</p>
<br/>
<p><h4>4. Direitos e Deveres do Elearning EaD</h4>
4.1 O Elearning EaD permitir&aacute; acesso 24 (vinte e quatro) horas por dia, 07 (sete) dias por semana, resguardados os tempos de disponibilidade de cada Treinamento contratado. Ressalvadas as exce&ccedil;&otilde;es dispostas no item 4.2 deste Termos de Uso.<br />
4.2 O Elearning EaD disponibilizar&aacute; o servi&ccedil;o de acesso contratado pelo Usu&aacute;rio, nos Termos e Condi&ccedil;&otilde;es Gerais para o Treinamento ou Curso escolhido, podendo eventualmente, o acesso sofrer interrup&ccedil;&otilde;es devido a problemas fortuitos e diversos, alheios &agrave; vontade do Elearning EaD, tais como falta de energia, indisponibilidade de Provedor, falhas de sistema de transmiss&atilde;o, entre outros. Quaisquer desses acontecimentos n&atilde;o ensejar&atilde;o preju&iacute;zo para o Usu&aacute;rio, que ter&aacute; sua reposi&ccedil;&atilde;o Educacional garantida.<br />
4.3 O Elearning EaD reserva-se o direito de interromper os Servi&ccedil;os Educacionais, com o seu devido Cancelamento, caso haja tentativa, por parte do Usu&aacute;rio, de modificar, adaptar, converter, reverter a engenharia, descompilar ou desmontar qualquer parte do Site. A mesma san&ccedil;&atilde;o ser&aacute; aplicada ao Usu&aacute;rio que publicar ou transmitir v&iacute;rus, worm, Cavalo de Tr&oacute;ia, easter egg, time bomb, spyware ou outro c&oacute;digo, arquivo ou programa de computador que seja prejudicial ou invasivo ou cuja inten&ccedil;&atilde;o seja danificar ou tomar controle da opera&ccedil;&atilde;o, ou monitorar o uso de qualquer hardware, software ou equipamento, e usar o Site para violar os direitos legais de terceiros para obter ou coletar informa&ccedil;&otilde;es de identifica&ccedil;&atilde;o pessoal dos outros Usu&aacute;rios/Alunos.<br />
4.4. O Elearning EaD n&atilde;o se responsabiliza por danos profissionais ou pessoais, em virtude da visualiza&ccedil;&atilde;o do seu perfil de Usu&aacute;rio no Site por quaisquer terceiros, j&aacute; que a disponibiliza&ccedil;&atilde;o das fotos s&atilde;o opcionais e p&uacute;blicas para visualiza&ccedil;&atilde;o e divulga&ccedil;&atilde;o.<br />
4.5. O Elearning EaD n&atilde;o se responsabiliza por eventuais danos decorrentes do acesso Il&iacute;cito por terceiros ao Site valendo-se do uso do Login e Senha, que seja de uso exclusivo de Usu&aacute;rio.<br />
4.6 Em nenhuma circunst&acirc;ncia o Elearning EaD ou seus Fornecedores poder&atilde;o ser responsabilizados por quaisquer danos incluindo - mas n&atilde;o se limitando a - lucros cessantes, interrup&ccedil;&atilde;o de neg&oacute;cios ou perda de informa&ccedil;&atilde;o, que resultem do uso ou da incapacidade de usar os materiais disponibilizados, mesmo que o Elearning EaD tenha sido comunicado da possibilidade de tais danos. Como algumas jurisdi&ccedil;&otilde;es proibem a exclus&atilde;o e limita&ccedil;&atilde;o da responsabilidade por danos consequenciais ou incidentais, as limita&ccedil;&otilde;es acima n&atilde;o se aplicariam a voc&ecirc;, Usu&aacute;rio.</p>
<br/>
<p><h4>5. Direitos e Deveres do Usu&aacute;rio</h4>
5.1. O Usu&aacute;rio ser&aacute; respons&aacute;vel pela correta e id&ocirc;nea utiliza&ccedil;&atilde;o do Login e Senha, de seu uso exclusivo durante o(s) Treinamento(s) contratado(s). A disponibiliza&ccedil;&atilde;o de Conte&uacute;do Educacional de propriedade do Elearning EaD e do Professor respons&aacute;vel, n&atilde;o ensejar&aacute; possibilidade de distribuir, copiar, transmitir, exibir, reutilizar, reproduzir, publicar, licenciar, vender ou fazer qualquer outro tipo de uso comercial, sem a permiss&atilde;o por escrito, conforme a Lei n&ordm; 9.610, de 19 de fevereiro de 1998, e Lei n&ordm; 10.695, de 1 de julho de 2003, que regulam os Direitos Autorais no Brasil.<br />
5.2. O Usu&aacute;rio dever&aacute; providenciar, por conta pr&oacute;pria, seu acesso &agrave; internet e os requisitos m&iacute;nimos para o funcionamento do Ambiente Virtual de Aprendizagem, dispon&iacute;vel no portal Elearning EaD.<br />
5.3 O Usu&aacute;rio se compromete a comunicar imediatamente ao Elearning EaD a eventual perda ou roubo de sua senha de acesso, assim como qualquer risco de acesso a ela por terceiros. &Eacute; recomend&aacute;vel ao Usu&aacute;rio trocar de senha periodicamente, o que pode ser feito acessando-se a p&aacute;gina no Site.<br />
5.4. Os dados pessoais, entre esses seu pr&oacute;prio CPF, s&atilde;o de sua total responsabilidade, arcando com san&ccedil;&otilde;es civis e penais que eventualmente gerarem no uso indevido do documento de outrem. Lembrando que estes dados dever&atilde;o ser preenchidos com responsabilidade no Cadastro de Usu&aacute;rio.<br />
5.5. O Usu&aacute;rio assume todos os &ocirc;nus e responsabilidades decorrentes de seus atos e desvio de conduta como aluno do Elearning EaD, respondendo ainda por atos que terceiros praticarem em seu nome, por meio de uso de seu Login e Senha de acesso.</p>
<br/>
<p><h4>6 . Den&uacute;ncia de abusos e viola&ccedil;&atilde;o</h4>
6.1 O Usu&aacute;rio se compromete a denunciar quaisquer abusos ou viola&ccedil;&atilde;o destes Termos e Condi&ccedil;&otilde;es de Uso ou de quaisquer direitos de terceiros que observar e/ou for v&iacute;tima quando da utiliza&ccedil;&atilde;o do Site. O Usu&aacute;rio deve utilizar o canal disponibilizado no Site para comunica&ccedil;&atilde;o com o Elearning EaD.<br />
6.2 Todo conte&uacute;do que o Usu&aacute;rio publica utilizando qualquer f&oacute;rum de discuss&atilde;o &eacute; uma informa&ccedil;&atilde;o que, por sua natureza e caracter&iacute;stica, &eacute; p&uacute;blica, aberta e n&atilde;o confidencial. Ao revelar dados pessoais, tais como seu nome e endere&ccedil;o de e-mail nos coment&aacute;rios, o Usu&aacute;rio aceita e compreende que essa informa&ccedil;&atilde;o pode ser coletada e usada por outras pessoas para se comunicarem com ele, sem que seja imput&aacute;vel qualquer responsabilidade ao Elearning EaD. Desta forma, o Elearning EaD recomenda que o Usu&aacute;rio seja, portanto, cuidadoso ao decidir compartilhar qualquer dado pessoal em qualquer website.</p>
<br/>
<p><h4>7. Legisla&ccedil;&atilde;o aplic&aacute;vel</h4>
7.1 Estes Termos e Condi&ccedil;&otilde;es de Uso s&atilde;o governados e interpretados segundo as leis da Rep&uacute;blica Federativa do Brasil e todas as disputas, a&ccedil;&otilde;es e outros assuntos relacionados ser&atilde;o determinados de acordo com essa legisla&ccedil;&atilde;o, e previstas no Contrato de Presta&ccedil;&atilde;o de Servi&ccedil;os Educacionais.<br />
7.2 Considerando o que disp&otilde;e o C&oacute;digo de Defesa do Consumidor em seu artigo 54, o Contrato de Presta&ccedil;&atilde;o de Servi&ccedil;os Educacionais supra citado caracteriza-se como um contrato de ades&atilde;o. Quando da realiza&ccedil;&atilde;o da matr&iacute;cula, o aluno ou o seu respons&aacute;vel legal adere ao mesmo, sem haver a necessidade de sua assinatura. Por este motivo, o Contrato de Presta&ccedil;&atilde;o de Servi&ccedil;os Educacionais, registrado em Cart&oacute;rio de T&iacute;tulos e Documentos, dever&aacute; ser visualizado pelo aluno.<br />
</p>